### ISSUE TITLE
postgresql dump support

### ISSUE THREAD

**Issue by edbond** [astrails/safe#4]
see pg_dump

**Comment by vitaly** [comment]
support was added on the 'refactoring' branch. please test.

**Comment by ramontayag** [comment]
Mine doesn't work.

<pre>
$ sudo /opt/ruby-enterprise-1.8.7-2010.01/bin/astrails-safe --verbose config/astrails_backup.rb 
command: pg_dump -i -x -O --username='ramon'   bridler|gzip
pg_dump: [archiver (db)] connection to database "bridler" failed: FATAL:  Ident authentication failed for user "ramon"
</pre>


However, looking at the pgdump.rb (http://github.com/astrails/safe/blob/1e4bd6af5dc94abd588d7206385e24cf778e9f47/lib/astrails/safe/pgdump.rb), the command formed is something like this (this prints out the sql):

<pre>
pg_dump --username=ramon bridler
</pre>


I then thought it may be a permissions issue, so I did this:

<pre>
sudo pg_dump --username=ramon bridler
</pre>


and I got this error:

<pre>
pg_dump: [archiver (db)] connection to database "bridler" failed: FATAL:  Ident authentication failed for user "ramon"
</pre>


It looks to be a very similar error message. Then I think the problem is that astrails-safe runs the script with sudo powers, not as "ramon".
